language: c++
sudo: required
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - cmake
            - make
            - gdb
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - STATS_TEST_USE_STDVEC="y"
        - CCOV=gcov-10 && CXXCOV=gcov-10
        - STATS_TEST_RUN_COV="y"
      compiler: gcc          # works on Precise and Trusty

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - cmake
            - make
            - gdb
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - STATS_TEST_USE_STDVEC="y"
        - CCOV=gcov-10 && CXXCOV=gcov-10
        - STATS_TEST_RUN_COV="y"


    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - cmake
            - make
            - gdb
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - STATS_TEST_USE_STDVEC="y"
        - CCOV=gcov-10 && CXXCOV=gcov-10
        - STATS_TEST_RUN_COV="y"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - cmake
            - make
            - gdb
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - STATS_TEST_USE_STDVEC="y"
        - CCOV=gcov-10 && CXXCOV=gcov-10
        - STATS_TEST_RUN_COV="y"

before_install:
  - eval "${MATRIX_EVAL}"
script:
  - cd paulkokos/CppReference
  - git clone https://github.com/paulkokos/CppReference.git
  - cd CppReference
  - ./configure && make && make test